### ISSUE TITLE
Suggestion: Improving Indentation Guides to Reflect Scope More Intuitively

### ISSUE THREAD

**Issue by ColeHoward** [replit/codemirror-indentation-markers#17]
Hi Everyone,
I noticed that the indentation guides extend to the end of the enclosing scope, even if there's no code in the additional lines. This approach is valid, but it differs from the behavior of other common editors like VS Code. 

I propose adjusting the indentation guides to terminate at the last line of code within a scope. I believe this subtle adjustment could provide a cleaner and more intuitive visual representation of code structure. 

#### A Couple Examples:

**Before:**
```plaintext
class Foo:
|   def __init__(self, bars):
|   |   self.bars = []
|   |   if bars:
|   |   |   self.bars = bars
|   |   |
|   |   |
|   def print_bars(self):
|   |   for element in self.bars:
|   |   |    print(element)
|   |   |
|   |   |
...
```

**After:**
```plaintext
class Foo:
|   def __init__(self, bars):
|   |   self.bars = []
|   |   if bars:
|   |   |   self.bars = bars
|       
|       
|   def print_bars(self):
|   |   for element in self.bars:
|   |   |    print(element)


...
```

And then for languages that use curly braces, it would better represent the scope of the code even if the brackets aren't properly formatted:

**Before:**
```plaintext
if (true){
|   doSomething()}
|
|
...
```

**After:**
```plaintext
if (true){
|   doSomething()}

...
```
#### Question
- Would this change be in line with the goals and direction of the project?

If there's any interest, I can go ahead and make a pull request. It's a pretty easy change.

**Comment by sergeichestakov** [comment]
hey @ColeHoward! thanks for the issue. this sounds reasonable although it would be nice if this were a preference as this distinction is largely subjective. definitely open to PRs!

**Comment by ColeHoward** [comment]
Hey @sergeichestakov ! I think making it an option is a good idea and more flexible. I'll make a PR soon. Thanks!

**Comment by sergeichestakov** [comment]
this is fixed by https://github.com/replit/codemirror-indentation-markers/pull/18

thanks again for the PR!
