### ISSUE TITLE
Indentation markers are off some times

### ISSUE THREAD

**Issue by bmeurer** [replit/codemirror-indentation-markers#20]
I'm currently exploring hooking up this plugin to Chrome DevTools by default (as requested in [crbug/1479986](https://crbug.com/1479986)). However testing this a on a bunch of files, in some cases (for example the `proxy.js` file in the coffee-cart.netlify.app test app) the indentation seems off by 1 or 2 levels.

![image](https://github.com/replit/codemirror-indentation-markers/assets/815988/211540c1-b88e-4e47-a0d9-15fedac5be34)

**Comment by sergeichestakov** [comment]
hey @bmeurer! thanks for the report and super excited to hear that the Chrome DevTools team is considering using our extension!

what is your indentation level set to? the extension uses the [getIndentUnit](https://codemirror.net/docs/ref/#language.getIndentUnit) helper to determine where to render the indentation markers which relies on the `indentUnit` facet (or `tabSize` facet if using tabs) under the hood. Setting those facet values explicitly should tweak where the markers get rendered.

Although, now that I'm thinking about it it would also be neat to be able to pass overrides to these values in as config to the extension but the above should do the trick for now.

**Comment by bmeurer** [comment]
Thanks for getting back on this. I was already worried that it might be due to our indentation detection (which I think infers the `indentUnit`). I'll need to dig deeper into this.

So you don't have any plans to make this independent of indentation detection?

**Comment by sergeichestakov** [comment]
We didn't have plans to add a config option for it but we can! I think that's a good idea and should be pretty straightforward. For now, it will rely on the facet which I think is generally suited for most use cases (for consistency with everything else that relies on indentation in the editor such as the "Tab" keybinding)

**Comment by bmeurer** [comment]
The problem is indeed our indentation detection, as suspected. If I disable that (on the file mentioned above) and set indentation to 4 spaces, everything's perfect:

![image](https://github.com/replit/codemirror-indentation-markers/assets/815988/d0080b12-9a6d-4ea5-9e55-2ad18c76e962)

**Comment by bmeurer** [comment]
Sorry for the noise. This extension works perfectly, but DevTools needs to get a better, more reliable indentation detection.
