### ISSUE TITLE
Suggestion: remove indent on blank lines

### ISSUE THREAD

**Issue by tomaszkiewicz** [replit/codemirror-indentation-markers#6]
Hi, 

Assuming you have a document in markdown like:

```
- one
  - two
  - three

four
five
```

The plugin draws a line on first **four** lines, which doesn't look good.

I found a quick fix to hide line in blank lines after the indent by adding that to my theme:

```
 "span span.cm-indentation-marker": {
      display: "none",
    },
```

Maybe you'll find it useful and add it to the code as a default :) (or do it in some nicer way than ugly CSS hack ;) )

**Comment by sergeichestakov** [comment]
Thanks for the issue! This should no longer be the case in the latest update as we're relying on a totally new implementation that does not draw indent for those lines. Cheers!

**Comment by jtojnar** [comment]
There still appear to be some cases where this happens in 6.4.2:

![image](https://github.com/replit/codemirror-indentation-markers/assets/705123/3676e62d-27aa-47a4-a812-9f17c8aee1cf)
