### ISSUE TITLE
Emptyish lines have misaligned indentation markers

### ISSUE THREAD

**Issue by bates64** [replit/codemirror-indentation-markers#7]
Lines that are empty or only contain whitespace have indentation markers that appear a few units to the left of lines that have content:

![](https://cdn.glitch.global/7ca73229-053c-4222-bb01-9737c31c214b/f010f67c-8256-44bf-ae8c-b7e9abdffa4a.image.png?v=1672802101658)

Live repro: https://repro-codemirror-indentation-markers-7.glitch.me

**Comment by sergeichestakov** [comment]
This should be fixed in the latest updates as we are now relying on a brand new reimplementation but please let me know if you're still experiencing this
